version: '2'

volumes:
  mysql-data:
  portus-data:
  registry-data:
  portus-certs:
  registry-certs:

x-portus-environment:
  &portus-environment
    PORTUS_MACHINE_FQDN_VALUE: ${PORTUS_FQDN}

    # MySQL DB
    PORTUS_DB_HOST: mysql
    PORTUS_DB_DATABASE: portus_db
    PORTUS_DB_USERNAME: portus
    # PORTUS_DB_PASSWORD: ${MYSQL_PASSWORD}
    PORTUS_DB_POOL: '5'

    # Secrets
    # PORTUS_SECRET_KEY_BASE: ${SECRET_KEY_BASE}
    PORTUS_KEY_PATH: /mnt/certs/key.pem
    # PORTUS_PASSWORD: ${PORTUS_PASSWORD}

    # Email
    PORTUS_EMAIL_FROM: ${EMAIL_FROM}
    PORTUS_EMAIL_REPLY_TO: ${EMAIL_REPLY_TO}
    PORTUS_EMAIL_SMTP_ENABLED: 'true'
    PORTUS_EMAIL_SMTP_ADDRESS: ${EMAIL_SMTP_ADDRESS}
    PORTUS_EMAIL_SMTP_PORT: ${EMAIL_SMTP_PORT}
    PORTUS_EMAIL_SMTP_SSL_TLS: ${EMAIL_SMTP_SSL_TLS}
    PORTUS_EMAIL_SMTP_USER_NAME: ${EMAIL_SMTP_USER_NAME}
    # PORTUS_EMAIL_SMTP_PASSWORD: ${EMAIL_SMTP_PASSWORD}

services:
  portus:
    image: opensuse/portus:head
    container_name: portus
    depends_on:
      - mysql
      - portus-certs-generator
    links:
      - mysql
    environment:
      <<: *portus-environment
      # Server
      PORTUS_DELETE_ENABLED: 'true'
      PORTUS_GRAVATAR_ENABLED: 'false'
      # Since we have no nginx, portus have to serve the static files
      RAILS_SERVE_STATIC_FILES: 'true'
      # certificates are configured in load-balancer
      PORTUS_CHECK_SSL_USAGE_ENABLED: 'false'
      PORTUS_SIGNUP_ENABLED: 'false'
    volumes:
      - portus-data:/srv/Portus/public
      - portus-certs:/mnt/certs:ro
    links:
      - "registry:${REGISTRY_FQDN}"

  background:
    image: opensuse/portus:head
    depends_on:
      - portus
      - mysql
      - portus-certs-generator
    links:
      - mysql
    environment:
      <<: *portus-environment
      # Background process
      PORTUS_BACKGROUND: 'true'
      PORTUS_BACKGROUND_REGISTRY_ENABLED: 'true'
      PORTUS_BACKGROUND_SYNC_ENABLED: 'true'
      PORTUS_BACKGROUND_SYNC_STRATEGY: update-delete

      # Garbage collector
      PORTUS_DELETE_GARBAGE_COLLECTOR_ENABLED: 'true'
      PORTUS_DELETE_GARBAGE_COLLECTOR_OLDER_THAN: '7'
      PORTUS_DELETE_GARBAGE_COLLECTOR_KEEP_LATEST: '1'

      # Theoretically not needed, but cconfig's been buggy on this...
      CCONFIG_PREFIX: PORTUS
    volumes:
      - portus-data:/srv/Portus/public
      - portus-certs:/mnt/certs:ro
    links:
      - "registry:${REGISTRY_FQDN}"

  mysql:
    # with version 10.0.35 and 10.3.6 we got an error:
    # /usr/sbin/mysqld: Too many arguments (first extra is 'NAMES').
    image: mariadb:10.3.5
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci --init-connect='SET NAMES UTF8;' --innodb-flush-log-at-trx-commit=0
    environment:
      # MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: portus_db
      MYSQL_USER: portus
      # MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - mysql-data:/var/lib/mysql

  registry:
    image: registry:2.6
    depends_on:
      - portus-certs-generator
      - registry-letsencrypt
    container_name: registry
    environment:
      # Storage
      REGISTRY_STORAGE_DELETE_ENABLED: 'true'

      # Authentication
      REGISTRY_AUTH_TOKEN_REALM: https://${PORTUS_FQDN}/v2/token
      REGISTRY_AUTH_TOKEN_SERVICE: ${REGISTRY_FQDN}:5000
      REGISTRY_AUTH_TOKEN_ISSUER: ${PORTUS_FQDN}
      REGISTRY_AUTH_TOKEN_ROOTCERTBUNDLE: /mnt/certs/cert.pem
      REGISTRY_AUTH_TOKEN_AUTOREDIRECT: 'false'

      # SSL
      REGISTRY_HTTP_TLS_CERTIFICATE: /certificates/fullchain.pem
      REGISTRY_HTTP_TLS_KEY: /certificates/privkey.pem

      # Portus endpoint
      REGISTRY_NOTIFICATIONS_ENDPOINTS: >
        - name: portus
          url: http://portus:3000/v2/webhooks/events
          timeout: 2000ms
          threshold: 5
          backoff: 1s

      # Debug
      # REGISTRY_LOG_LEVEL: debug
    volumes:
      - registry-data:/var/lib/registry
      - portus-certs:/mnt/certs:ro
      - registry-certs:/certificates:ro
    ports:
      - 5000:5000

  portus-certs-generator:
    image: mgbi/openssl-certs
    environment:
      SSL_SUBJECT: portus
      CA_EXPIRE: '7300'   # 20 lat
      SSL_EXPIRE: '7300'
      DEBUG: 0
    volumes:
      - portus-certs:/certs

  registry-letsencrypt:
    image: mgbi/rancher-letsencrypt:v1.0.0
    environment:
      API_VERSION: Production
      CERT_NAME: ${REGISTRY_FQDN}
      DNS_RESOLVERS: 8.8.8.8:53,8.8.4.4:53
      DOMAINS: ${REGISTRY_FQDN}
      EMAIL: ${LETSENCRYPT_EMAIL}
      EULA: 'Yes'
      PROVIDER: HTTP
      PUBLIC_KEY_TYPE: RSA-2048
      RENEWAL_PERIOD_DAYS: '21'
      RENEWAL_TIME: '3'
      RUN_ONCE: 'false'
    volumes:
      - registry-certs:/etc/letsencrypt/production/certs/${REGISTRY_FQDN}
