version: '2'

services:
  lb:
    lb_config:
      certs:
        - ${PORTUS_FQDN}
        - ${CONCOURSE_FQDN}
      default_cert: ${PORTUS_FQDN}
      port_rules:
      # Portus service
      - protocol: http
        path: /.well-known/acme-challenge/
        hostname: ${PORTUS_FQDN}
        source_port: 80
        target_port: 80
        service: letsencrypt
      - protocol: https
        hostname: ${PORTUS_FQDN}
        source_port: 443
        target_port: 3000
        service: portus

      # Docker Registry service
      - protocol: http
        path: /.well-known/acme-challenge/
        hostname: ${REGISTRY_FQDN}
        source_port: 80
        target_port: 80
        service: registry-letsencrypt
      #- protocol: tcp
      #  source_port: 5000
      #  target_port: 5000
      #  service: registry

      # Concourse CI service
      - protocol: http
        path: /.well-known/acme-challenge/
        hostname: ${CONCOURSE_FQDN}
        source_port: 80
        target_port: 80
        service: concourse/letsencrypt
      - protocol: https
        hostname: ${CONCOURSE_FQDN}
        source_port: 443
        target_port: 8080
        service: concourse/web

      config: |-
        global
            log 127.0.0.1:8514 local0 debug

        defaults
            log global
            option httplog
            option logasap

        frontend 80
            acl 80_well_known_acme_challenge__path path_beg -i /.well-known/acme-challenge/
            redirect scheme https code 302 if !80_well_known_acme_challenge__path !{ ssl_fc }
