version: '2'

services:
  lb:
    lb_config:
      certs:
        - ${PORTUS_FQDN}
      default_cert: ${PORTUS_FQDN}
      port_rules:
      - protocol: http
        path: /.well-known/acme-challenge/
        hostname: ${PORTUS_FQDN}
        source_port: 80
        target_port: 80
        service: letsencrypt
      - protocol: http
        hostname: ${PORTUS_FQDN}
        source_port: 80
        target_port: 3000
        service: portus
      - protocol: http
        path: /.well-known/acme-challenge/
        hostname: ${REGISTRY_FQDN}
        source_port: 80
        target_port: 80
        service: registry-letsencrypt
      - protocol: https
        hostname: ${PORTUS_FQDN}
        source_port: 443
        target_port: 3000
        service: portus
      #- protocol: tcp
      #  hostname: ${REGISTRY_FQDN}
      #  source_port: 5000
      #  target_port: 5000
      #  service: registry
      - protocol: tcp
        hostname: ${REGISTRY_FQDN}
        source_port: 443
        target_port: 5000
        service: registry