version: '2'

services:
  lb:
    lb_config:
      certs:
        - ${PORTUS_FQDN}
      default_cert: ${PORTUS_FQDN}
      port_rules:
      - protocol: http
        path: /.well-known/acme-challenge/
        hostname: ${PORTUS_FQDN}
        source_port: 80
        target_port: 80
        service: letsencrypt
      - protocol: http
        hostname: ${PORTUS_FQDN}
        source_port: 80
        target_port: 3000
        service: portus
      - protocol: http
        path: /.well-known/acme-challenge/
        hostname: ${REGISTRY_FQDN}
        source_port: 80
        target_port: 80
        service: registry-letsencrypt
      - protocol: https
        hostname: ${PORTUS_FQDN}
        source_port: 443
        target_port: 3000
        service: portus
      #- protocol: tcp
      #  source_port: 5000
      #  target_port: 5000
      #  service: registry
      #- protocol: tcp
      #  source_port: 443
      #  target_port: 5000
      #  service: registry
      #  priority: 2
      config: |-
        global
            log 127.0.0.1:8514 local0 debug

        defaults
            log global
            option httplog
            option logasap

        frontend 80
            acl 80_well_known_acme_challenge__path path_beg -i /.well-known/acme-challenge/
            redirect scheme https code 302 if !80_well_known_acme_challenge__path !{ ssl_fc }